dependencies:
  - path: dependencies/main
    git: 'https://github.com/chimpwizards/_git/wand'
    tags:
      - dependencies
  - path: dependencies/commons/
    git: 'https://github.com/chimpwizard-wand/_git/commons'
    tags:
      - dependencies
      - commons
  - path: dependencies/spells/config
    git: 'https://github.com/chimpwizard-wand/_git/spell-config'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/shell
    git: 'https://github.com/chimpwizard-wand/_git/spell-shell'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/hello
    git: 'https://github.com/chimpwizard-wand/_git/spell-hello'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/spells
    git: 'https://github.com/chimpwizard-wand/_git/spell-spells'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/workspace
    git: 'https://github.com/chimpwizard-wand/_git/spell-workspace'
    tags:
      - dependencies
      - spells

