name: wand
organization: 'git@github.com:chimpwizards-wand'
dependencies:
  - path: dependencies/main
    git: 'git@github.com:chimpwizards-wand/main.git'
    tags:
      - dependencies
  - path: dependencies/commons/
    git: 'git@github.com:chimpwizards-wand/commons.git'
    tags:
      - dependencies
      - commons
  - path: dependencies/spells/config
    git: 'git@github.com:chimpwizards-wand/spell-config.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/shell
    git: 'git@github.com:chimpwizards-wand/spell-shell.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/hello
    git: 'git@github.com:chimpwizards-wand/spell-hello.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/spells
    git: 'git@github.com:chimpwizards-wand/spell-spells.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/workspace
    git: 'git@github.com:chimpwizards-wand/spell-workspace.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/abc
    git: 'git@github.com:chimpwizards-wand/wand-abc.git'
    tags:
      - dependencies
      - abc
  - path: dependencies/xyz/xyz2
    git: 'git@github.com:chimpwizards-wand/wand-xyz2.git'
    tags:
      - dependencies
      - xyz
      - xyz2
  - path: dependencies/xyz3
    git: 'git@github.com:chimpwizards-wand/wand-xyz3.git'
    tags:
      - dependencies
      - xyz3
scripts:
  hello: ./scripts/hello.sh
  start-ssh: scripts/start-ssh.sh
