dependencies:
  - path: dependencies/main
    git: 'git@github.com:chimpwizards-wand/main.git'
    tags:
      - dependencies
  - path: dependencies/commons/
    git: 'git@github.com:chimpwizards-wand/commons.git'
    tags:
      - dependencies
      - commons
  - path: dependencies/spells/config
    git: 'git@github.com:chimpwizards-wand/spell-config.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/shell
    git: 'git@github.com:chimpwizards-wand/spell-shell.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/hello
    git: 'git@github.com:chimpwizards-wand/spell-hello.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/spells
    git: 'git@github.com:chimpwizards-wand/spell-spells.git'
    tags:
      - dependencies
      - spells
  - path: dependencies/spells/workspace
    git: 'git@github.com:chimpwizards-wand/spell-workspace.git'
    tags:
      - dependencies
      - spells
scripts:
  hello: ./scripts/hello.sh
  abc: scripts/abc
